# Generated by Django 4.1.5 on 2023-03-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_event_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Subject Owner'),
        ),
    ]
